import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "./globals.css";
import { QueryProvider } from "./providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Envolvemos toda la app con QueryProvider para que
// React Query esté disponible en toda la aplicación

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col bg-gray-50">
        {/* QueryProvider debe envolver todo el contenido */}
        <QueryProvider>
          {/* Navbar persistente */}
          <header className="bg-red-600 text-white shadow-lg sticky top-0 z-50">
            <nav className="container mx-auto px-4 py-4">
              <div className="flex items-center justify-between">
                <Link 
                  href="/" 
                  className="text-2xl font-bold hover:text-yellow-300 transition-colors"
                >
                  🔴 PokéDex
                </Link>
                <div className="space-x-4">
                  <Link 
                    href="/" 
                    className="hover:text-yellow-300 transition-colors"
                  >
                    Lista Principal
                  </Link>
                </div>
              </div>
            </nav>
          </header>

          {/* Contenido dinámico */}
          <main className="flex-1 container mx-auto px-4 py-8">
            {children}
          </main>

          {/* Footer persistente */}
          <footer className="bg-gray-800 text-white mt-auto">
            <div className="container mx-auto px-4 py-6 text-center">
              <p className="mb-2">
                PokéDex - Aplicación con React Query y Next.js
              </p>
              <p className="text-sm text-gray-400">
                Datos obtenidos de PokeAPI.co usando Client-side Data Fetching
              </p>
            </div>
          </footer>
        </QueryProvider>
      </body>
    </html>
  );
}

